server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_support
    password: mysql123
    username: vilius
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect