jwt:
  secret: 0A493CD6D27B6DE2A4745CF077DAA33F9C3E0E881471EB2495110ACA91BC56C1

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_support
    password: mysql123
    username: vilius
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false